language: cpp
sudo: required
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
osx_image: xcode7
dist: trusty
branches:
  only:
  - master
  - stage
  - travis_fix2
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y libunittest++-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install unittest-cpp; fi
  - g++ --version
  - clang++ --version
  - java -version
install: cmake CMakeLists.txt
script: make && build/unitTests
after_script: rm -f *.hpl *.log
